SELECT * FROM customer ORDER BY LAST_NAME ASC

SELECT * FROM customer ORDER BY LAST_NAME DESC

SELECT COUNT(USERNAME) FROM customer
WHERE SALARY > 300000;

SELECT AVG(NVL(SALARY,0)) AS AVERAGE_SALARY 
FROM customer

SELECT USERNAME, FIRST_NAME, LAST_NAME, SALARY FROM customer
WHERE NVL(SALARY,0) < (SELECT AVG(NVL(SALARY,0)) as AVG_SAL FROM customer);

SELECT FIRST_NAME, LAST_NAME FROM customer
WHERE UPPER(LAST_NAME) LIKE '%S%'

SELECT FIRST_NAME, LAST_NAME, NVL(TO_CHAR(PROFESSION),'jobless') AS PROFESSION FROM customer
WHERE LOWER(FIRST_NAME) LIKE '%s';

SELECT NVL(INITCAP(PROFESSION),'jobless') AS PROFESSION, COUNT (*) AS QUANTITY
FROM customer
GROUP BY NVL(INITCAP(PROFESSION),'jobless')
ORDER BY NVL(INITCAP(PROFESSION),'jobless') DESC;

SELECT INITCAP(FIRST_NAME) ||' '|| INITCAP(LAST_NAME) AS CUSTOMER_NAME FROM customer


SELECT COUNT(*) AS LOGGED_IN FROM customer
WHERE USERNAME = 'King25'
AND PASSWD = 'asdf1234';

SELECT COUNT(*) AS LOGGED_IN FROM customer
WHERE USERNAME = 'KING25'
AND PASSWD = 'ASDF1234';

SELECT USERNAME, PASSWD, REG_DATE FROM customer
WHERE REG_DATE < TO_DATE('2000-01-01','YYYY-MM-DD');

SELECT USERNAME, PASSWD, REG_DATE FROM customer
WHERE REG_DATE > TO_DATE('2001-01-01','YYYY-MM-DD');
AND REG_DATE < TO_DATE('2003-10-01','YYYY-MM-DD');

SELECT USERNAME, PASSWD, FIRST_NAME, LAST_NAME FROM customer
WHERE (LOWER(LAST_NAME) = 'nyberg' OR  LOWER(LAST_NAME) = 'kvist')
AND NOT LOWER(FIRST_NAME) = 'roger'

SELECT FIRST_NAME, LAST_NAME, SALARY FROM customer
WHERE SALARY = (SELECT MAX(SALARY) FROM customer);

SELECT FIRST_NAME, LAST_NAME, SALARY FROM customer
WHERE SALARY = (SELECT MIN(SALARY) FROM customer);

SELECT FIRST_NAME, LAST_NAME FROM customer
WHERE PROFESSION IS NULL